const EVENT = {
  LOGIN_PANEL: 'LOGIN_PANEL',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  ROUTE_CHANGE: 'ROUTE_CHANGE',
  PREVIEW: 'PREVIEW',
  PREVIEW_CLOSE: 'PREVIEW_CLOSE',
  PREVIEW_CLOSED: 'PREVIEW_CLOSED',
  PREVIEW_POST: 'PREVIEW_POST',
  NAV_EDIT: 'NAV_EDIT',
  NAV_CREATE_POST: 'NAV_CREATE_POST',
  REFRESH_POSTS: 'REFRESH_POSTS',

  // menu
  SIDEBAR_MENU_CHANGE: 'SIDEBAR_MENU_CHANGE',
  // ROUTE_COMMUNITY_MENU_CHANGE: 'ROUTE_COMMUNITY_MENU_CHANGE',

  // admin
  NAV_CREATE_COMMUNITY: 'NAV_CREATE_COMMUNITY',
  NAV_UPDATE_COMMUNITY: 'NAV_UPDATE_COMMUNITY',

  // community
  NAV_SET_COMMUNITY: 'NAV_SET_COMMUNITY',

  // category
  NAV_CREATE_CATEGORY: 'NAV_CREATE_CATEGORY',
  NAV_UPDATE_CATEGORY: 'NAV_UPDATE_CATEGORY',
  NAV_SET_CATEGORY: 'NAV_SET_CATEGORY',
  // thread
  NAV_CREATE_THREAD: 'NAV_CREATE_THREAD',
  NAV_SET_THREAD: 'NAV_SET_THREAD',
  // tag
  NAV_SET_TAG: 'NAV_SET_TAG',
  NAV_CREATE_TAG: 'NAV_CREATE_TAG',
  NAV_UPDATE_TAG: 'NAV_UPDATE_TAG',
  // permission
  NAV_CREATE_PERMISSION: 'NAV_CREATE_PERMISSION',
  NAV_UPDATE_PERMISSION: 'NAV_UPDATE_PERMISSION',

  DRAFT_INSERT_SNIPPET: 'DRAFT_INSERT_SNIPPET',
}

export default EVENT
