export const TYPE = {
  APP_HEADER_ID: 'APP_HEADER_ID',

  CHEATSHEET_ROOT_PAGE: 'CHEATSHEET_ROOT_PAGE',
  COMMUNITIES_ROOT_PAGE: 'COMMUNITIES_ROOT_PAGE',
  COMMUNITY_PAGE: 'COMMUNITY_PAGE',
  POST_PAGE: 'POST_PAGE',
  ACTIVITIES_ROOT_PAGE: 'ACTIVITIES_ROOT_PAGE',

  POST: 'POST',
  JOB: 'JOB',
  REPO: 'REPO',
  VIDEO: 'VIDEO',
  FAVORITE: 'FAVORITE',
  STAR: 'STAR',
  WATCH: 'WATCH',
  REACTION: 'reaction',
  UNDO_REACTION: 'undoReaction',
  POST_PREVIEW_VIEW: 'POST_PREVIEW_VIEW',
  PREVIEW_ACCOUNT_VIEW: 'PREVIEW_ACCOUNT_VIEW',
  PREVIEW_ACCOUNT_EDIT: 'PREVIEW_ACCOUNT_EDIT',
  PREVIEW_ROOT_STORE: 'PREVIEW_ROOT_STORE',
  PREVIEW_CREATE_POST: 'PREVIEW_CREATE_POST',

  // admin
  PREVIEW_CREATE_COMMUNITY: 'PREVIEW_CREATE_COMMUNITY',
  PREVIEW_UPDATE_COMMUNITY: 'PREVIEW_UPDATE_COMMUNITY',
  // >> community
  PREVIEW_SET_COMMUNITY: 'PREVIEW_SET_COMMUNITY',
  // >> tags
  PREVIEW_SET_TAG: 'PREVIEW_SET_TAG',
  PREVIEW_CREATE_TAG: 'PREVIEW_CREATE_TAG',
  PREVIEW_UPDATE_TAG: 'PREVIEW_UPDATE_TAG',
  // >> categories
  PREVIEW_CREATE_CATEGORY: 'PREVIEW_CREATE_CATEGORY',
  PREVIEW_UPDATE_CATEGORY: 'PREVIEW_UPDATE_CATEGORY',
  PREVIEW_SET_CATEGORY: 'PREVIEW_SET_CATEGORY',
  // >> threads
  PREVIEW_CREATE_THREAD: 'PREVIEW_CREATE_THREAD',
  PREVIEW_SET_THREAD: 'PREVIEW_SET_THREAD',
  // >> permission
  PREVIEW_CREATE_PERMISSION: 'PREVIEW_CREATE_PERMISSION',
  PREVIEW_UPDATE_PERMISSION: 'PREVIEW_UPDATE_PERMISSION',

  // PAGE STATE
  LOADING: 'LOADING',
  NOT_FOUND: 'NOT_FOUND',
  RESULT: 'RESULT',
  // filters
  ASC_INSERTED: 'ASC_INSERTED',
  DESC_INSERTED: 'DESC_INSERTED',
  MOST_LIKES: 'MOST_LIKES',
  MOST_DISLIKES: 'MOST_DISLIKES',

  // ACTION EVENTS
  POSTS_REFRESH: 'POSTS_REFRESH',
  POSTS_CONTENT_REFRESH: 'POSTS_CONTENT_REFRESH',
  JOBS_CONTENT_REFRESH: 'JOBS_CONTENT_REFRESH',
  COMMUNITIES_REFRESH: 'COMMUNITIES_REFRESH',
  TAGS_REFRESH: 'TAGS_REFRESH',
  GATEGORIES_REFRESH: 'GATEGORIES_REFRESH',

  USERS_REFRESH: 'USERS_REFRESH',
}

export default TYPE
