export const ERR = {
  CRAPHQL: 'CRAPHQL',
  PARSE_CHEATSHEET_MD: 'PARSE_CHEATSHEET_MD',
  NETWORK: 'NETWORK',
  NOT_FOUND: 'NOT_FOUND',
  TIMEOUT: 'TIMEOUT',
}

export const EVENT = {
  LOGIN_PANEL: 'LOGIN_PANEL',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  PREVIEW: 'PREVIEW',
  PREVIEW_CLOSE: 'PREVIEW_CLOSE',
  PREVIEW_CLOSED: 'PREVIEW_CLOSED',
  PREVIEW_POST: 'PREVIEW_POST',
  NAV_EDIT: 'NAV_EDIT',
  NAV_CREATE_POST: 'NAV_CREATE_POST',
  REFRESH_POSTS: 'REFRESH_POSTS',

  DRAFT_INSERT_SNIPPET: 'DRAFT_INSERT_SNIPPET',
}

export const TYPE = {
  CHEATSHEET_ROOT_PAGE: 'CHEATSHEET_ROOT_PAGE',
  COMMUNITIES_ROOT_PAGE: 'COMMUNITIES_ROOT_PAGE',
  COMMUNITY_PAGE: 'COMMUNITY_PAGE',
  POST_PAGE: 'POST_PAGE',
  ACTIVITIES_ROOT_PAGE: 'ACTIVITIES_ROOT_PAGE',

  POST: 'POST',
  JOB: 'JOB',
  FAVORITE: 'FAVORITE',
  STAR: 'STAR',
  WATCH: 'WATCH',
  REACTION: 'reaction',
  UNDO_REACTION: 'undoReaction',
  POST_PREVIEW_VIEW: 'POST_PREVIEW_VIEW',
  PREVIEW_ACCOUNT_VIEW: 'PREVIEW_ACCOUNT_VIEW',
  PREVIEW_ACCOUNT_EDIT: 'PREVIEW_ACCOUNT_EDIT',
  PREVIEW_ROOT_STORE: 'PREVIEW_ROOT_STORE',
  PREVIEW_CREATE_POST: 'PREVIEW_CREATE_POST',

  // PAGE STATE
  LOADING: 'LOADING',
  NOT_FOUND: 'NOT_FOUND',
  RESULT: 'RESULT',
  // filters
  ASC_INSERTED: 'ASC_INSERTED',
  DESC_INSERTED: 'DESC_INSERTED',
  MOST_LIKES: 'MOST_LIKES',
  MOST_DISLIKES: 'MOST_DISLIKES',
  // Admin
  C_UTILS: 'C_UTILS',
  C_POSTS: 'C_POSTS',
  C_JOBS: 'C_JOBS',
  C_ACTIVITIES: 'C_ACTIVITIES',
  C_CHEATSHEETS: 'C_CHEATSHEETS',
  C_EDITORS: 'C_EDITORS',
  C_THREADS: 'C_THREADS',
  C_TAGS: 'C_TAGS',
  C_SUBSCRIBERS: 'C_SUBSCRIBERS',
  C_COMMUNITIES_ID: 'C_COMMUNITIES_ID',
  C_USERS_ID: 'C_USERS_ID',
  // Admin Communites Root
  C_R_TOP: 'C_R_TOP',
  C_R_CATEGORIES: 'C_R_CATEGORIES',
  C_R_EDITORS: 'C_R_EDITORS',
  C_R_POSTS: 'C_R_POSTS',
  // Admin Users Root
  U_R_REGISTER: 'U_R_REGISTER',
  U_R_PAYS: 'U_R_PAYS',
  U_R_PASSPORTS: 'U_R_PASSPORTS',
  U_R_ROLES: 'U_R_ROLES',
}
